export const nodes = [
    {
      id: 1,
      name: "Alice Johnson",
      email: "alice.johnson@example.com",
      status: "Active",
      lastLogin: "2024-03-15T14:30:00Z",
      deals: 12,
    },
    {
      id: 2,
      name: "Bob Smith",
      email: "bob.smith@example.com",
      status: "Inactive",
      lastLogin: "2024-02-28T09:15:00Z",
      deals: 5,
    },
    {
      id: 3,
      name: "Charlie Brown",
      email: "charlie.brown@example.com",
      status: "Pending",
      lastLogin: "2024-03-10T17:45:00Z",
      deals: 8,
    },
    {
      id: 4,
      name: "David Wilson",
      email: "david.wilson@example.com",
      status: "Active",
      lastLogin: "2024-03-19T11:05:00Z",
      deals: 15,
    },
    {
      id: 5,
      name: "Emily Davis",
      email: "emily.davis@example.com",
      status: "Inactive",
      lastLogin: "2024-01-20T21:30:00Z",
      deals: 3,
    },
    {
      id: 6,
      name: "Franklin Harris",
      email: "franklin.harris@example.com",
      status: "Pending",
      lastLogin: "2024-03-12T08:50:00Z",
      deals: 7,
    },
    {
      id: 7,
      name: "Grace Moore",
      email: "grace.moore@example.com",
      status: "Active",
      lastLogin: "2024-03-18T15:20:00Z",
      deals: 20,
    },
    {
      id: 8,
      name: "Henry Clark",
      email: "henry.clark@example.com",
      status: "Inactive",
      lastLogin: "2024-02-25T10:40:00Z",
      deals: 9,
    },
    {
      id: 9,
      name: "Ivy Martinez",
      email: "ivy.martinez@example.com",
      status: "Pending",
      lastLogin: "2024-03-14T13:10:00Z",
      deals: 11,
    },
    {
      id: 10,
      name: "Jack Thompson",
      email: "jack.thompson@example.com",
      status: "Active",
      lastLogin: "2024-03-19T18:55:00Z",
      deals: 18,
    },
    {
      id: 11,
      name: "Alice Johnson",
      email: "alice.johnson@example.com",
      status: "Active",
      lastLogin: "2024-03-15T14:30:00Z",
      deals: 12,
    },
    {
      id: 12,
      name: "Bob Smith",
      email: "bob.smith@example.com",
      status: "Inactive",
      lastLogin: "2024-02-28T09:15:00Z",
      deals: 5,
    },
    {
      id: 13,
      name: "Charlie Brown",
      email: "charlie.brown@example.com",
      status: "Pending",
      lastLogin: "2024-03-10T17:45:00Z",
      deals: 8,
    },
    {
      id: 14,
      name: "David Wilson",
      email: "david.wilson@example.com",
      status: "Active",
      lastLogin: "2024-03-19T11:05:00Z",
      deals: 15,
    },
    {
      id: 15,
      name: "Emily Davis",
      email: "emily.davis@example.com",
      status: "Inactive",
      lastLogin: "2024-01-20T21:30:00Z",
      deals: 3,
    },
    {
      id: 16,
      name: "Franklin Harris",
      email: "franklin.harris@example.com",
      status: "Pending",
      lastLogin: "2024-03-12T08:50:00Z",
      deals: 7,
    },
    {
      id: 17,
      name: "Grace Moore",
      email: "grace.moore@example.com",
      status: "Active",
      lastLogin: "2024-03-18T15:20:00Z",
      deals: 20,
    },
    {
      id: 18,
      name: "Henry Clark",
      email: "henry.clark@example.com",
      status: "Inactive",
      lastLogin: "2024-02-25T10:40:00Z",
      deals: 9,
    },
    {
      id: 19,
      name: "Ivy Martinez",
      email: "ivy.martinez@example.com",
      status: "Pending",
      lastLogin: "2024-03-14T13:10:00Z",
      deals: 11,
    },
    {
      id: 20,
      name: "Jack Thompson",
      email: "jack.thompson@example.com",
      status: "Active",
      lastLogin: "2024-03-19T18:55:00Z",
      deals: 18,
    },
    {
      id: 21,
      name: "Alice Johnson",
      email: "alice.johnson@example.com",
      status: "Active",
      lastLogin: "2024-03-15T14:30:00Z",
      deals: 12,
    },
    {
      id: 22,
      name: "Bob Smith",
      email: "bob.smith@example.com",
      status: "Inactive",
      lastLogin: "2024-02-28T09:15:00Z",
      deals: 5,
    },
    {
      id: 23,
      name: "Charlie Brown",
      email: "charlie.brown@example.com",
      status: "Pending",
      lastLogin: "2024-03-10T17:45:00Z",
      deals: 8,
    },
    {
      id: 24,
      name: "David Wilson",
      email: "david.wilson@example.com",
      status: "Active",
      lastLogin: "2024-03-19T11:05:00Z",
      deals: 15,
    },
    {
      id: 25,
      name: "Emily Davis",
      email: "emily.davis@example.com",
      status: "Inactive",
      lastLogin: "2024-01-20T21:30:00Z",
      deals: 3,
    },
    {
      id: 26,
      name: "Franklin Harris",
      email: "franklin.harris@example.com",
      status: "Pending",
      lastLogin: "2024-03-12T08:50:00Z",
      deals: 7,
    },
    {
      id: 27,
      name: "Grace Moore",
      email: "grace.moore@example.com",
      status: "Active",
      lastLogin: "2024-03-18T15:20:00Z",
      deals: 20,
    },
    {
      id: 28,
      name: "Henry Clark",
      email: "henry.clark@example.com",
      status: "Inactive",
      lastLogin: "2024-02-25T10:40:00Z",
      deals: 9,
    },
    {
      id: 29,
      name: "Ivy Martinez",
      email: "ivy.martinez@example.com",
      status: "Pending",
      lastLogin: "2024-03-14T13:10:00Z",
      deals: 11,
    },
    {
      id: 30,
      name: "Jack Thompson",
      email: "jack.thompson@example.com",
      status: "Active",
      lastLogin: "2024-03-19T18:55:00Z",
      deals: 18,
    },
    {
      id: 31,
      name: "Alice Johnson",
      email: "alice.johnson@example.com",
      status: "Active",
      lastLogin: "2024-03-15T14:30:00Z",
      deals: 12,
    },
    {
      id: 32,
      name: "Bob Smith",
      email: "bob.smith@example.com",
      status: "Inactive",
      lastLogin: "2024-02-28T09:15:00Z",
      deals: 5,
    },
    {
      id: 33,
      name: "Charlie Brown",
      email: "charlie.brown@example.com",
      status: "Pending",
      lastLogin: "2024-03-10T17:45:00Z",
      deals: 8,
    },
    {
      id: 34,
      name: "David Wilson",
      email: "david.wilson@example.com",
      status: "Active",
      lastLogin: "2024-03-19T11:05:00Z",
      deals: 15,
    },
    {
      id: 35,
      name: "Emily Davis",
      email: "emily.davis@example.com",
      status: "Inactive",
      lastLogin: "2024-01-20T21:30:00Z",
      deals: 3,
    },
    {
      id: 36,
      name: "Franklin Harris",
      email: "franklin.harris@example.com",
      status: "Pending",
      lastLogin: "2024-03-12T08:50:00Z",
      deals: 7,
    },
    {
      id: 37,
      name: "Grace Moore",
      email: "grace.moore@example.com",
      status: "Active",
      lastLogin: "2024-03-18T15:20:00Z",
      deals: 20,
    },
    {
      id: 38,
      name: "Henry Clark",
      email: "henry.clark@example.com",
      status: "Inactive",
      lastLogin: "2024-02-25T10:40:00Z",
      deals: 9,
    },
    {
      id: 39,
      name: "Ivy Martinez",
      email: "ivy.martinez@example.com",
      status: "Pending",
      lastLogin: "2024-03-14T13:10:00Z",
      deals: 11,
    },
    {
      id: 40,
      name: "Jack Thompson",
      email: "jack.thompson@example.com",
      status: "Active",
      lastLogin: "2024-03-19T18:55:00Z",
      deals: 18,
    },
  ];
  